import { Slider } from '@mui/material'
import Head from 'next/head'
import DeleteIcon from "@mui/icons-material/Delete"
export default function Home() {
  return (
    <div className="bg-teal-300/60 h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slider defaultValue={30} />
      <Slider
        defaultValue={30}
        className="text-teal-600"
        componentsProps={{ thumb: { className: 'rounded-sm text-red-500' } }}
      />
      <DeleteIcon sx={{color: "primary.main"}} />
    </div>
  )
}
